// <auto-generated />
namespace telerikerpService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderIsOnlineandStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderIsOnlineandStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201812011113519_Order IsOnline and Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
