#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ArtGalleryCRM.Droid.Resource", IsApplication=true)]

namespace ArtGalleryCRM.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int primary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int primaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int splash_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int statusBar_background = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int window_background = 2130771973;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int add_new = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int add_order = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int art_placeholder = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int btn_stat_notify = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int delete = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int download_error_placeholder = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int download_placeholder = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int edit = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int error_round = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int gray_circle = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int ic_about = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int ic_chat_bot = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int ic_chat_reply = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int ic_chat_user = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int ic_customers = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int ic_dialog = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int ic_employees = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int ic_help = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int ic_launcher = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int ic_list = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int ic_menu = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int ic_orders = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int ic_products = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int ic_settings = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int ic_shipping = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int ic_stat_notify = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int ic_tab = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int market = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int master_header_logo = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int master_logo_75 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int menu = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int next_chevron = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int ninja = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int profile_photo = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int refresh = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int save = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int sign_in = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int splash_screen = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int Welcome1 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int Welcome2 = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int Welcome3 = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int Welcome4 = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int Welcome5 = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int Welcome6 = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int splash = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppCompatDialogStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MyTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MyTheme_Base = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int MyTheme_Splash = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int Theme_Splash = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
